feeds:
  - https://levnocestovani.cz/feed
  - https://zaletsi.cz/feed
  - https://www.cestujlevne.com/feed
  - https://www.fly4free.com/feed/
  - https://www.honzovyletenky.cz/feed/

filters:
  include_keywords: []

  exclude_keywords:
    - do Egypta
    - Egypt
    - egypt
    - do Tuniska
    - Tunisko
    - tunisko
    - do Turecka
    - Turecko
    - turecko
